#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Displays information about subdomains.

domain_information() {
    local result
    local record_type
    result=$(dig "$2.$1" +short)
    if [ -n "$result" ]; then
        record_type=$(dig "$2.$1" | awk '/ANSWER SECTION/ {getline; print $4}')
        echo "The subdomain $2 is a $record_type record and points to $result"
    else
        echo "The subdomain $2 does not exist."
    fi
}

if [ "$#" == 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [<subdomain>]"
fi

