#!/usr/bin/env bash
# Installs Nginx.

sudo apt-get update
sudo apt-get install -y nginx

mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

# Create an Nginx server block
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
}
EOF

# Restart Nginx using the service command
sudo service nginx restart
