#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.

apt-get update
apt-get install -y nginx

# Remove the default configuration file
rm -f /etc/nginx/sites-available/default

# Create a new configuration file for Nginx
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }
}
EOF

# Create the "Hello World" index.html as before
mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

# Restart Nginx using the service command
service nginx restart
