#!/usr/bin/env bash
# This script displays the content of a the file /etc/passwd
# Only display: username, user id, home directory path for the user.

file='/etc/passwd'

while read -r line; do
	echo "$line" | cut -d ':' -f1,3,6
done < $file
