#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop.
# On the 9th iteration it sizplays "Hi" after "Best School".

i=0

while [ $i -lt 10 ]; do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	((i++))
done
