#!/usr/bin/env bash
# This script displays numbers from 1 to 20.
# It displays "bad luck from China" after the number 4.
# It displays "bad luck from japan" after the number 9.
# It displays "bad luck from Italy" after the number 17.

i=1

while [ $i -le 20 ]
do
	echo "$i"

	case $i in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac
	(( i++ ))
done
