#!/usr/bin/env bash
# This script displays te time for 12 hours and 59 minutes.
# Display hours from 0 to 12.
# Display minutes from 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		(( minute++ ))

		if [ $minute -eq 60 ]
		then
			(( hour++ ))
		fi
	done
	(( minute=1 ))
done
